
<h2>Login</h2>

<?php echo $this->tag->form(["login",'class' =>'form']); ?>


<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->textField(["email",'class' => 'form-control col-6']); ?>
</p>

<p>
    <label for="email">Password</label>
    <?php echo $this->tag->textField(["password",'class' => 'form-control col-6']); ?>
</p>
<p>
    <label for="email">Not a User ?</label>
    <?php echo $this->tag->linkTo("signup","Sign Up"); ?>
</p>

<div class="row small text-danger mb-2 mt-0">
    <?php 
    if(isset($msg)){
        echo $msg;
    }
    ?>
</div>

<p>
    <?php echo $this->tag->submitButton(["Log in",'class' => 'btn btn-primary']); ?>
</p>

</form>

<?php

// print_r($data);
?>


