
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Blogger</title>
</head>

<body>
    <header class='row container-fluid mt-3'>
        <div class='col-3 h3'><a href='http://localhost:8080/' class='text-decoration-none'>The Blogger</a></div>
        <div class='col-2'></div>
        <div class='col-4'><input type='text'>
            <div class=' ms-2 btn btn-primary'>Search</div>
        </div>
        <div class='col-1'>
        <?php echo $this->tag->linkTo(["login/", "Login", 'class' => 'btn btn-secondary']); ?>
        </div>
        <div class='col-1'>
        <?php echo $this->tag->linkTo(["login/signout", "Sign Out", 'class' => 'btn btn-secondary']); ?>
        </div>
        <hr class='mt-4'>
    </header>
    <?php

?>
<main class="container mb-5">
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
            <h1 class="display-4 fst-italic"><?php echo $post[0]->title; ?></h1>
            <p class="lead my-3"><?php echo $post[0]->description; ?></p>
            <p class="lead mb-0"><?php echo $post[0]->date; ?></p>
        </div>
    </div>
    <div class='h2 mt-4 mb-2'>
        <?php  echo $user[0]->username; ?>
        
    </div>
    <div class="small"> - Auther </div>
    <div class='mt-4 mb-2'>

        <?php echo $post[0]->article ?>

    </div>
</main>