<?php
//   global $settings;
// print_r($data);
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>Blogger</title>
</head>

<body>
    <header class='row container-fluid mt-3'>
        <div class='col-3 h3'><a href='http://localhost:8080/' class='text-decoration-none'>The Blogger</a></div>
        <div class='col-2'></div>
        <div class='col-4'><input type='text'>
            <div class=' ms-2 btn btn-primary'>Search</div>
        </div>
        <div class='col-1'>
        <?php echo $this->tag->linkTo(["login/", "Login", 'class' => 'btn btn-secondary']); ?>
        </div>
        <div class='col-1'>
        <?php echo $this->tag->linkTo(["login/signout", "Sign Out", 'class' => 'btn btn-secondary']); ?>
        </div>
        <hr class='mt-4'>
    </header>
    <?php
// print_r($data);
?>

<main class="container">
    <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
        <div class="col-md-6 px-0">
            <h1 class="display-4 fst-italic">Title of a longer featured blog post</h1>
            <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
            <p class="lead mb-0"><a href="./blog/signup.php" class="text-white fw-bold">Get Started .....</a></p>
        </div>
    </div>
    <div class="row g-5 mt-5">
        <div class="col-md-8">
            <h3 class="pb-4 mb-4 fst-italic border-bottom">
                Read
            </h3>
            <?php

            foreach ($posts as $post) {
                if ($post->status == 'Published') {
                    echo "<div class='row mb-2'>
                   <div class='col'> 
                   <div class='row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative'>
                           <div class='col p-4 d-flex flex-column position-static'>
                               <strong class='d-inline-block mb-2 text-primary'>World</strong>
                               <h3 class='mb-0'>$post->title</h3>
                               <div class='mb-1 text-muted'>$post->date</div>
                               <p class='card-text mb-auto'>$post->description</p>
                               <form method='post' action='http://localhost:8080/index/fullarticle' >
                                <input type='hidden' name='blog_id' value='$post->blog_id' />
                                <input type='hidden' name='user_id' value='$post->post_user_id' />
                               <input type='submit' class='stretched-link border-0' name='continue' value='Continue Reading ...'></input>
                               </form >     
                               </div>
                           <div class='col-auto d-none d-lg-block'>
                               <svg class='bd-placeholder-img' width='200' height='250' xmlns='http://www.w3.org/2000/svg' role='img' aria-label='Placeholder: Thumbnail' preserveAspectRatio='xMidYMid slice' focusable='false'>
                                   <title>Placeholder</title>
                                   <rect width='100%' height='100%' fill='#55595c' /><text x='50%' y='50%' fill='#eceeef' dy='.3em'>Thumbnail</text>
                               </svg>
                           </div>
                       </div>
                   </div>
               </div>";
                }
            }
            ?>

        </div>
        <div class="col-md-4">
            <div class="position-sticky" style="top: 2rem;">
                <div class="p-4 mb-3 bg-light rounded">
                    <h4 class="fst-italic h3 mb-3">Trending</h4>
                    <?php foreach ($posts as $post) {
                        if ($post->trending == 'Yes') {
                            echo "<div class='row border p-3'>
                            <p class='mt-2 h5'> $post->title</p>
                            <p class='small mt-0'>$post->description</p>
                        </div>
                        <hr>
                            ";
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</main>



<footer class='text-muted py-5 bg-dark'>
        <div class='container'>
            <p class='float-end mb-1'>
                <a href='#'>Back to top</a>
            </p>
            <p class='mb-1'>&copy; CEDCOSS Technologies</p>
        </div>
    </footer>
</body>

</html>